site_name: LVWebApp Documentation
site_description: Documentation for the LVWebApp project
site_url: https://your-docs-url.com/

theme:
  name: material
  palette:
    primary: indigo
    accent: indigo
  features:
    - navigation.tabs
    - navigation.sections
    - search.suggest
    - search.highlight

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.tabbed
  - pymdownx.critic
  - pymdownx.tasklist:
      custom_checkbox: true

nav:
  - Home: index.md
  - Getting Started: 
    - Installation: getting-started/installation.md
    - Configuration: getting-started/configuration.md
  - Components: 
    - Overview: components/overview.md
  - API Reference: 
    - Overview: api/overview.md 